console.log(' ');
console.log(' ');
console.log(' ');
console.log('All good. Go drink a 🍺');
console.log(' ');
console.log(' ');
console.log(' ');
console.log(' ');
console.log(' ');
console.log(' ');